export const GLOBAL_TEXT = {
  footer: {
    disclaimer: 'Disclaimer: $ACME WAS MADE FOR A FAN AND HAS NO VALUE. DON’T RISK MONEY YOU ARE AFRAID OF LOSING. THE PRICE MAY GO UP OR IT MAY GO DOWN. WE ARE NOT RESPONSIBLE FOR THE PRICE OF THE TOKEN.'
  }
}